spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_test
    username: sa
    password: rootroot

security:
  token: "eyJhbGciOiJSUzUxMiJ9.eyJzdWIiOiJqb2huLmRvZSIsImV4cCI6MTcwNzA3MzMxNn0.Rwb4SBI7wH0jsAKem0dzF0kDfV7tV5dICvz9jEfCY4u5zKSdzl_I3YRiw16-ad3GTuRSa2DO8ZajAv00ywFTiassH6lTYcrmn0jUdm3FY464ojHuGDTAWHCqHkuE0akglRup91Us8Sa3az2-PiBdqjncZY8hvVSeDj55VSprJoMQOAjEpxUCZZE_ZhiPqqrEZn80Bg6fIa1KpRXp0qafKYbmzNw0CEkb0US2TH_1qqNL0lCHgNUO2fWS08QsZmzbNrdsK_Y8xr3RMnEbMbll4oNsO-WTybW7AWLtW3E7VpTw1djWUD5RWnkPEaT3zuUK3kSwt8IKCsaj64J5aaa1CQ"

logging:
  level:
    root: debug